apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-voting-app
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-voting-app
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}
