apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: result
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: result
  type: NodePort
status:
  loadBalancer: {}
